### ISSUE TITLE
深度图预测很差

### ISSUE THREAD

**Issue by zhang5957** [XYZ-qiyh/Learning-MVS-PyTorch#2]
你好，我使用你提供的mvsnet预训练模型来预测，发现深度图效果很差，这个怎么解决呢？
![image](https://user-images.githubusercontent.com/60083899/145934428-14a67b37-0fff-42e7-b155-a6818ec919ae.png)

**Comment by XYZ-qiyh** [comment]
你好，请问你的实验设置是怎样的？

**Comment by zhang5957** [comment]
> 

我在eval的时候，将读取的图片缩放到（640，512）大小，同样的内参也进行了缩放，其他的没变
