### ISSUE TITLE
预测精度问题

### ISSUE THREAD

**Issue by ajunyo** [XYZ-qiyh/Learning-MVS-PyTorch#3]
好兄弟想问下，你复现了原文的精度吗？确实还差很多，用的3090训练的

**Comment by XYZ-qiyh** [comment]
你好， @ajunyo 
1. 使用MVSNet_pytorch的代码的预训练模型直接进行测试，PyTorch 1.7.0及以上版本需要将https://github.com/xy-guo/MVSNet_pytorch/blob/e0f2ae3d7cb2dd13807b775f2075682eaa7f1521/models/module.py#L127-L128 中`grid_sample` 中加上Align_Corner=False, 应该可以跑出README文件中的精度。
2. 在3090机器上自己训练并测试，3090上的PyTorch版本至少是1.7.0或以上，这个和PyTorch1.2.0训练的模型还是有差别的，但是什么原因导致的，这个我还不清楚。

**Comment by ajunyo** [comment]
谢谢你，今天才看到回复你实在不好意思 ，感谢感谢

**Comment by ajunyo** [comment]
大佬有联系方式么，想交流一下

**Comment by XYZ-qiyh** [comment]
你好，可以在微信群里探讨哈
